import { createFileRoute } from "@tanstack/react-router";
import { useStore } from "@/lib/store";
import { ZONES, ZONE_COORDS, severityColor, type Zone } from "@/lib/mock-data";

export const Route = createFileRoute("/_app/advisory")({
  head: () => ({ meta: [{ title: "Public Advisory — Bengaluru Traffic" }] }),
  component: Advisory,
});

function Advisory() {
  const { state } = useStore();
  const top = state.events.filter((e) => e.severity === "Critical" || e.severity === "High").slice(0, 5);

  const zoneSev: Record<Zone, string> = {} as never;
  for (const z of ZONES) zoneSev[z] = "Normal";
  for (const ev of state.events.slice(0, 40)) {
    const rank = ["Normal", "Medium", "High", "Critical"];
    if (rank.indexOf(ev.severity) > rank.indexOf(zoneSev[ev.zone])) zoneSev[ev.zone] = ev.severity;
  }

  return (
    <div className="-m-6 p-10 min-h-[calc(100vh-3.5rem)]" style={{ background: "linear-gradient(180deg, #15151A, #0A0A0A)" }}>
      <div className="max-w-4xl mx-auto fade-up">
        <header className="mb-8 pb-6 border-b border-border">
          <h1 className="text-3xl font-semibold tracking-tight">Bengaluru Traffic Advisory</h1>
          <p className="text-sm text-muted-foreground mt-1">Public Information — Updated Live · {new Date().toLocaleString()}</p>
        </header>

        <section className="mb-8">
          <h2 className="text-lg font-semibold mb-4">Current advisories</h2>
          <div className="space-y-3">
            {top.length === 0 && <p className="text-sm text-muted-foreground">No major disruptions reported at this time. Travel as planned.</p>}
            {top.map((e) => (
              <article key={e.id} className="p-4 rounded border border-border" style={{ borderLeft: `3px solid ${severityColor(e.severity)}` }}>
                <div className="text-xs mono text-muted-foreground">{new Date(e.ts).toLocaleTimeString()}</div>
                <div className="text-base mt-1">
                  {e.severity === "Critical" ? "Severe congestion" : "Heavy congestion"} expected near <strong>{e.zone}</strong> due to {e.cause.toLowerCase()}.
                  Estimated clearance: approx. {new Date(e.ts + e.durationMin * 60000).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}.
                  Consider alternate routes via Outer Ring Road.
                </div>
              </article>
            ))}
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-semibold mb-4">City zone overview</h2>
          <svg viewBox="0 0 900 720" className="w-full hud-card" style={{ height: 360, background: "#0A0A0A" }}>
            {ZONES.map((z) => {
              const c = ZONE_COORDS[z];
              const sev = zoneSev[z];
              const col = severityColor(sev);
              return (
                <g key={z}>
                  <circle cx={c.x} cy={c.y} r={12} fill={col} fillOpacity={0.2} stroke={col} />
                  <text x={c.x + 14} y={c.y + 4} fill="#F5F5F5" fontSize="11" fontFamily="Inter">{z}</text>
                </g>
              );
            })}
          </svg>
        </section>

        <footer className="text-xs text-muted-foreground border-t border-border pt-4">
          This advisory is generated by an automated traffic intelligence system and is provided for informational purposes.
          For emergencies, contact local traffic police at <span className="mono">112</span>.
        </footer>
      </div>
    </div>
  );
}