/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSystemHealthRouteImport } from './routes/_app.system-health'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppIncidentRecordsRouteImport } from './routes/_app.incident-records'
import { Route as AppHeatmapRouteImport } from './routes/_app.heatmap'
import { Route as AppForecastRouteImport } from './routes/_app.forecast'
import { Route as AppEventSimulatorRouteImport } from './routes/_app.event-simulator'
import { Route as AppCommandRouteImport } from './routes/_app.command'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAgentCenterRouteImport } from './routes/_app.agent-center'
import { Route as AppAdvisoryRouteImport } from './routes/_app.advisory'
import { Route as AppActivityLogRouteImport } from './routes/_app.activity-log'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSystemHealthRoute = AppSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentRecordsRoute = AppIncidentRecordsRouteImport.update({
  id: '/incident-records',
  path: '/incident-records',
  getParentRoute: () => AppRoute,
} as any)
const AppHeatmapRoute = AppHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppEventSimulatorRoute = AppEventSimulatorRouteImport.update({
  id: '/event-simulator',
  path: '/event-simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandRoute = AppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentCenterRoute = AppAgentCenterRouteImport.update({
  id: '/agent-center',
  path: '/agent-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisoryRoute = AppAdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityLogRoute = AppActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity-log': typeof AppActivityLogRoute
  '/advisory': typeof AppAdvisoryRoute
  '/agent-center': typeof AppAgentCenterRoute
  '/alerts': typeof AppAlertsRoute
  '/command': typeof AppCommandRoute
  '/event-simulator': typeof AppEventSimulatorRoute
  '/forecast': typeof AppForecastRoute
  '/heatmap': typeof AppHeatmapRoute
  '/incident-records': typeof AppIncidentRecordsRoute
  '/settings': typeof AppSettingsRoute
  '/system-health': typeof AppSystemHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity-log': typeof AppActivityLogRoute
  '/advisory': typeof AppAdvisoryRoute
  '/agent-center': typeof AppAgentCenterRoute
  '/alerts': typeof AppAlertsRoute
  '/command': typeof AppCommandRoute
  '/event-simulator': typeof AppEventSimulatorRoute
  '/forecast': typeof AppForecastRoute
  '/heatmap': typeof AppHeatmapRoute
  '/incident-records': typeof AppIncidentRecordsRoute
  '/settings': typeof AppSettingsRoute
  '/system-health': typeof AppSystemHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activity-log': typeof AppActivityLogRoute
  '/_app/advisory': typeof AppAdvisoryRoute
  '/_app/agent-center': typeof AppAgentCenterRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/command': typeof AppCommandRoute
  '/_app/event-simulator': typeof AppEventSimulatorRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/heatmap': typeof AppHeatmapRoute
  '/_app/incident-records': typeof AppIncidentRecordsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/system-health': typeof AppSystemHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity-log'
    | '/advisory'
    | '/agent-center'
    | '/alerts'
    | '/command'
    | '/event-simulator'
    | '/forecast'
    | '/heatmap'
    | '/incident-records'
    | '/settings'
    | '/system-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity-log'
    | '/advisory'
    | '/agent-center'
    | '/alerts'
    | '/command'
    | '/event-simulator'
    | '/forecast'
    | '/heatmap'
    | '/incident-records'
    | '/settings'
    | '/system-health'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/activity-log'
    | '/_app/advisory'
    | '/_app/agent-center'
    | '/_app/alerts'
    | '/_app/command'
    | '/_app/event-simulator'
    | '/_app/forecast'
    | '/_app/heatmap'
    | '/_app/incident-records'
    | '/_app/settings'
    | '/_app/system-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/system-health': {
      id: '/_app/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof AppSystemHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incident-records': {
      id: '/_app/incident-records'
      path: '/incident-records'
      fullPath: '/incident-records'
      preLoaderRoute: typeof AppIncidentRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/heatmap': {
      id: '/_app/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof AppHeatmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/event-simulator': {
      id: '/_app/event-simulator'
      path: '/event-simulator'
      fullPath: '/event-simulator'
      preLoaderRoute: typeof AppEventSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/command': {
      id: '/_app/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AppCommandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent-center': {
      id: '/_app/agent-center'
      path: '/agent-center'
      fullPath: '/agent-center'
      preLoaderRoute: typeof AppAgentCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advisory': {
      id: '/_app/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AppAdvisoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity-log': {
      id: '/_app/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AppActivityLogRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityLogRoute: typeof AppActivityLogRoute
  AppAdvisoryRoute: typeof AppAdvisoryRoute
  AppAgentCenterRoute: typeof AppAgentCenterRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppCommandRoute: typeof AppCommandRoute
  AppEventSimulatorRoute: typeof AppEventSimulatorRoute
  AppForecastRoute: typeof AppForecastRoute
  AppHeatmapRoute: typeof AppHeatmapRoute
  AppIncidentRecordsRoute: typeof AppIncidentRecordsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSystemHealthRoute: typeof AppSystemHealthRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityLogRoute: AppActivityLogRoute,
  AppAdvisoryRoute: AppAdvisoryRoute,
  AppAgentCenterRoute: AppAgentCenterRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppCommandRoute: AppCommandRoute,
  AppEventSimulatorRoute: AppEventSimulatorRoute,
  AppForecastRoute: AppForecastRoute,
  AppHeatmapRoute: AppHeatmapRoute,
  AppIncidentRecordsRoute: AppIncidentRecordsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSystemHealthRoute: AppSystemHealthRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
